### ISSUE TITLE
summary about TBD which are related with compiling with clang

### ISSUE THREAD

**Issue by unicornx** [aosp-riscv/chromium#2]
-  (1) Can's support following flags

```
cflags += [
"-Xclang",
"-add-plugin",
"-Xclang",
"find-bad-constructs",

"-Xclang",
"-plugin-arg-find-bad-constructs",
"-Xclang",
"raw-ref-template-as-trivial-member",
]
cflags += [
"-Xclang",
"-plugin-arg-find-bad-constructs",
"-Xclang",
"check-ipc",
]
cflags += [
"-Xclang",
"-add-plugin",
"-Xclang",
"blink-gc-plugin",
]
cflags += [
"-Xclang",
"-plugin-arg-blink-gc-plugin",
"-Xclang",
"dump-graph",
]
```
  Ref: https://groups.google.com/a/chromium.org/g/blink-dev/c/Ep4GJJHFNYI

- (2) `-Wno-unused-but-set-variable` has not been supported by clang 12 (current android clang), which is expected to be supported since clang 13
  Ref: https://reviews.llvm.org/rGcf49cae278b4e972cd2547d72f9ee7d9d69a3af4

- (3) combining the C++11 alias specifier and the GNU __attribute__ specifier is not supported

  Example: BASE_EXPORT uses GNU `__attribute__` cannot be mixed with C++11 alias, so we have to adjust this when compile with android clang 12.

```cpp
// FIXME: Currently, Android RISCV64 only supports clang version 12.0.x.
// Seems combining the C++11 alignas specifier and the GNU __attribute__ specifier are not supported.
// Ref: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69585#c5
// struct [[maybe_unused]] BASE_EXPORT ReentryGuard {
struct __attribute__((unused)) BASE_EXPORT ReentryGuard {
```

- (4) Following flags are not supported.
```
cflags += [
"-Xclang",
"-fdebug-compilation-dir",
"-Xclang",
".",
]
```
  Refs:
  - https://reviews.llvm.org/D97433
  - https://www.mail-archive.com/cfe-commits@lists.llvm.org/msg221553.html
  - https://bugs.chromium.org/p/chromium/issues/detail?id=1231236

- (5) `-Wno-deprecated-non-prototype` is not supprted

**Comment by unicornx** [comment]
@McKnight22 请看一下这个 issue 是否需要更新或者关闭？

**Comment by McKnight22** [comment]
> @McKnight22 请看一下这个 issue 是否需要更新或者关闭？

Since we already can build clang for chromium from scratch and clang_use_chrome_plugins can be enabled to build chrome_public_apk successfully based on the clang for chromium built from scratch by us, so I regard the issue can be closed.
