### ISSUE TITLE
why we need add libvpx?

### ISSUE THREAD

**Issue by unicornx** [aosp-riscv/chromium#32]
参考 https://github.com/McKnight22/chromium/commit/eaf70e3d660b70ea8458b4e32a9afaa025f14dc8

**Comment by McKnight22** [comment]
> 参考 [McKnight22@eaf70e3](https://github.com/McKnight22/chromium/commit/eaf70e3d660b70ea8458b4e32a9afaa025f14dc8)

The libvpx is required to be supported with RISCV64.
Please refer to https://github.com/google/android-riscv64/issues/17.

**Comment by unicornx** [comment]
But why you add this as dependency for chromium (it's new for chromium and is for riscv only). I think https://github.com/google/android-riscv64/issues/17 is just talk about libvpx2 for AOSP, not chromium.

**Comment by unicornx** [comment]
closed due to I'm not working on this now.
