### ISSUE TITLE
PR to google upstream mainline

### ISSUE THREAD

**Issue by unicornx** [aosp-riscv/chromium#40]
任务目标：我们尝试一下是否可以将目前我们的工作提交到 google upstream 的主线上去。我们需要尽早追踪上游的进展，并随时争取将我们的工作及时体现出来到官方主线上，***开源工作竞争是非常激烈的，因为我们面对的是 global，如果被别人抢先提交了对我们的工作是一个损失***。

实时追踪上游主线的好处还有可能发现我们的一些改动最新上游已经提供了甚至给出了更好的解法，特别地如果存在更好的解法，我们就基于 109 提交新的补丁和最新上游对齐。

本仓库新建 `riscv64_android_upstream` 分支，我们的目标就是维护该分支，使其和上游的 main 保持同步并逐步缩小该分支和 upstream 的 delta，一旦达到一致，我们的 upstream 工作就算完成了。在此过程中我们还要和开发板的开发工作同步，一个是看看能不能基于 upstream main + local hacked android ndk 都构建并在板子上运行，另外一方面还会跟踪开发板 109 版本的开发工作，将此期间可能发现的问题修复也及时补充到我们的 `riscv64_android_upstream` 上。

本 issue 作为该任务的 main entry，如果有其他问题可以另外提 issue 跟踪。

我想到的一些问题
- Q1: 如何向 chromium 上游提交 patch，需要看一下相关文档了解一下流程
- Q2: 如果是向上游提交估计要基于最新的主线，所以实际提交时需要将目前基于 109 的改动 catch up 到最新的 master 上去。具体可以再了解 Q1 的基础上看看别人是怎么提交的。这个如果有思路了，我们就在本仓库中实时同步 upstream 的 master 分支，然后你在 master 上拉开发分支，具体提交时我建议先在本仓库中做 internal review，确保ok后再向上游提交。
- Q3: 实际提交的内容需要仔细考虑，特别是我们目前测试并达不到完整的充分性，但是我觉得也不能等完全可以工作了再提交，可以挑一些确定只会影响 android + riscv64 的进行提交，具体提交时需要满足什么样的测试要求，这个我觉得可以和 google 上游的人讨论后看看怎么操作，目前我们也的确不清楚。
- Q4: 实际提交的内容同样需要分解，确保每次只提交一个相对独立的部分，目标是：小步快跑。
- Q5: 除了本仓库外，还有一些有依赖的仓库，譬如 ffmpeg 等不要忘记也是可以提交的。
- Q6: 工具链部分应该同样是最新需要考虑的部分，据我的了解，109 上我们打上的 clang 的补丁已经全部合入最新的 clang 主线了，所以我们要做的就是检查 chromium 最新的 master 上取的 clang 是否已经涵盖了我们需要的补丁。

请他问题请补充。

**Comment by McKnight22** [comment]
Q1: 如何向 chromium 上游提交 patch，需要看一下相关文档了解一下流程
A1: Contributing to Chromium, https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/contributing.md
&emsp;&emsp;Contributing to Chromium external repo, such as [v8](https://v8.dev/docs) and [Skia](https://skia.org/dev/contrib). Eg. https://skia.org/docs/dev/contrib/submit/

**Comment by unicornx** [comment]
我根据我自己的理解整理了一下目前 ffmpeg 可以 upstream 的部分，供参考：

https://chromium.googlesource.com/chromium/third_party/ffmpeg.git

这个仓库目前除了
- `./chromium/scripts/build_ffmpeg.py android riscv64`
- `./chromium/scripts/generate_gn.py`
- `./chromium/scripts/copy_config.sh`
这三个文件外，其他的修改都是一些自动产生的文件，并不需要提交，具体参考 [de7399e94ab2c148e6fd3a4f68b6cbc6354af697](https://github.com/aosp-riscv/ffmpeg/commit/de7399e94ab2c148e6fd3a4f68b6cbc6354af697) 的 commit 注释。

但是由于 `build_ffmpeg.py` 的执行依赖于 android ndk，所以目前看上去这部分还不能 upstream。

**Comment by unicornx** [comment]
我根据我自己的理解整理了一下目前 v8 可以 upstream 的部分，供参考：

https://github.com/aosp-riscv/v8

我觉得这些改动都是针对 android 的，可以尝试 upsteream。同样的问题可能无法编译验证，但至少不该影响当前的构建（! (android && riscv64)）

以下注意：
- 目前 v8 上有三个 commit，感觉是独立的修改，upstream 时注意还是分成三个 pr 提交，这个也是 general 的 rule，一个 commit 只修改一个 ***"相对独立的"*** 问题，这样 reviewer 也好看。如果你对 commit 的内容有疑问请及时找我讨论。
- 8284e6b269e6d2d51f4877dd3d95a337857cbf30 这个我觉得一定可以提交，目前的 master 只考虑了 gcc 构建，我们这么改可以确保 gcc 和 clang 都 pass，如果你不好测试验证 gcc，可以请 upstream 帮忙验证一下。
- e48b8935c93ee37115302933cd4e7959d7d5ef26 这个我有点记不清为啥要 disable libatomic 了，你可以看看这个问题在 upstream 的主线上是否依然存在，如果要改需要再看看具体原因，在提交时需要说清楚，不然 review 的时候别人问起来不好回答。我当时的 commit 上不知什么原因没有写清楚，现在也想不起来了。sorry :)

**Comment by unicornx** [comment]
我根据我自己的理解整理了一下目前 angle 可以 upstream 的部分，供参考：
https://github.com/aosp-riscv/angle

目前有三个 commits

- e9827ae03ebfa197acf225db8bd8108d950d8b52：这个只涉及 gn，可以尝试 pr ，看看上游怎么 comment
- d12176ee019fa0e23d8ca152adcbcd13f6357004 这个应该只会影响 android for riscv64，问题是无法编译验证，可以尝试pr ，看看 upstream 怎么说。
- 937ede49e6de44552597d455b8779a2b4989e399 这个和 2nd api 的支持相关，有关 2nd api 的修改建议专门作为一个主题和 upstream 讨论，当然也要看看上游对我们提交 android+riscv64 的态度和支持程度，最坏的情况就是，上游觉得我们现在提交 android+riscv64 还不是时候，那我们就要再重新计划了。

**Comment by unicornx** [comment]
我根据我自己的理解整理了一下目前 chromium 可以 upstream 的部分，供参考：
https://github.com/aosp-riscv/chromium

其实提交的原则和 v8，angle 这些小仓库是类似的，因为 chromium 的改动比较多且琐碎，我就不在这里仔细列出了。你可以根据自己的理解尝试做做，有问题及时讨论。

基本的原则我觉得可以归纳如下，有缺少你补充：
- 如果是涉及原来代码中的 bug 优先提交。
- 只会影响 android && riscv64 的改动（大部分应该属于这一类）先找一些小的尝试提交看看，目前主要问题可能就是因为 android ndk 的问题，导致 clang 做不出来也就无法编译我们的代码，最多能确保 gn 成功。还是先看看上游的接受态度，如果做了几个以后，感觉上游不愿意按照现在的状态接收，那我们也没有办法，这个问题你注意观察，如果现在实在不是时机那也没有办法，不用非要 upstream，我们后面再找机会。
- Makefile 部分的修改都是不用提交的。
- 如果是我们从 sifive 或者其他开发人员那参考借用来的 patch，我一般会在 commit 中说明，一般是一些 riscv64 通用性的改动，这些改动的产权不属于我们，所以不要提交。

**Comment by unicornx** [comment]
有关 https://chromium-review.googlesource.com/c/chromium/src/+/4528430

fixDexIfNecessary -> needsDexCompile -> odexPathFromApkPath

fixDexIfNecessary 有两处被调用，且对 api level > Q 的情况会被跳过（shouldSkipDexFix）
```cpp
private static boolean shouldSkipDexFix() {
       ......
       // All bugs are fixed after Q.
       if (Build.VERSION.SDK_INT > Build.VERSION_CODES.Q) {
            return true;
        }
```
- fixDexInBackground：有一处会调用该函数，chrome/android/java/src/org/chromium/chrome/browser/upgrade/PackageReplacedBroadcastReceiver.java，涉及 chrome 的 upgrade。
```java
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                DexFixer.fixDexInBackground();
            }
```
- scheduleDexFix: 有一处会调用该函数：
chrome/android/java/src/org/chromium/chrome/browser/base/SplitCompatApplication.java
```java
protected void attachBaseContext(Context context) {
......
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                // Fixes are never required before O (where "cmd package compile" does not exist).
                DexFixer.scheduleDexFix();
            }
```
参考 `docs/android_isolated_splits.md` 中 “Corrupted .odex (Android O MR1)”, 感觉也是和 chrome 升级操作有关。

总结，fixDexIfNecessary 中的相关逻辑在 platform level [O, Q] (android 8~10) 时会被调用，其他情况会被跳过。RISCV64 的支持应该至少是 15 以后的事情了，所以我觉得的确我们没有必要做这部分改动。

@McKnight22  我当时是参考 https://github.com/McKnight22/chromium/commit/ae5c9c73b516f6fa8ccf6ac8697718dc47cfd878#diff-c98a5d24d68efa950e15f1e4cce2a560244d0a4b5a36254dfcb87d0c8e9a3dde 做的这个修改，请检查一下当时为何要这么改，是影响了什么吗？ 我试了一下回退掉这个修改，编译 ok，运行测试了基本的打开页面，但因为测试不了 chrome 的升级操作，所以没有看到跑到上面的两处。

**Comment by McKnight22** [comment]
> 有关 https://chromium-review.googlesource.com/c/chromium/src/+/4528430
> 
> fixDexIfNecessary -> needsDexCompile -> odexPathFromApkPath
> 
> fixDexIfNecessary 有两处被调用，且对 api level > Q 的情况会被跳过（shouldSkipDexFix）
> 
> ```c++
> private static boolean shouldSkipDexFix() {
>        ......
>        // All bugs are fixed after Q.
>        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.Q) {
>             return true;
>         }
> ```
> 
> * fixDexInBackground：有一处会调用该函数，chrome/android/java/src/org/chromium/chrome/browser/upgrade/PackageReplacedBroadcastReceiver.java，涉及 chrome 的 upgrade。
> 
> ```java
>             if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
>                 DexFixer.fixDexInBackground();
>             }
> ```
> 
> * scheduleDexFix: 有一处会调用该函数：
>   chrome/android/java/src/org/chromium/chrome/browser/base/SplitCompatApplication.java
> 
> ```java
> protected void attachBaseContext(Context context) {
> ......
>             if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
>                 // Fixes are never required before O (where "cmd package compile" does not exist).
>                 DexFixer.scheduleDexFix();
>             }
> ```
> 
> 参考 `docs/android_isolated_splits.md` 中 “Corrupted .odex (Android O MR1)”, 感觉也是和 chrome 升级操作有关。
> 
> 总结，fixDexIfNecessary 中的相关逻辑在 platform level [O, Q] (android 8~10) 时会被调用，其他情况会被跳过。RISCV64 的支持应该至少是 15 以后的事情了，所以我觉得的确我们没有必要做这部分改动。
> 
> @McKnight22 我当时是参考 [McKnight22@ae5c9c7#diff-c98a5d24d68efa950e15f1e4cce2a560244d0a4b5a36254dfcb87d0c8e9a3dde](https://github.com/McKnight22/chromium/commit/ae5c9c73b516f6fa8ccf6ac8697718dc47cfd878#diff-c98a5d24d68efa950e15f1e4cce2a560244d0a4b5a36254dfcb87d0c8e9a3dde) 做的这个修改，请检查一下当时为何要这么改，是影响了什么吗？ 我试了一下回退掉这个修改，编译 ok，运行测试了基本的打开页面，但因为测试不了 chrome 的升级操作，所以没有看到跑到上面的两处。

我试图从自己的本地记录以及自己的repo中去找到此处修改的相关记录，但没有找到。此处修改我们先回退掉。

**Comment by unicornx** [comment]
closed due to I'm not working on this now.
